project_structure:
    build: build
    contracts: contracts
    scripts: scripts

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            gas_limit: 6721975
            accounts: 10
            evm_version: cancun
            block_time: 0
            default_balance: 1000000
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: cancun
    solc:
        version: 0.8.28
        viaIR: true
        optimizer:
            enabled: true
            runs: 1500
        remappings:
            - "@solady/=lib/solady/src/"
            - "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
            - "@governance/=lib/governance/contracts/"
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false